### ISSUE TITLE
Typerror when importing phasor module as in the documentation example

### ISSUE THREAD

**Issue by Mogit21** [engineerjoe440/ElectricPy#108]
The import in the step 3 of the "Installing / Getting Started" in the documentation is not working as expected

```python
# Setup
import electricpy as ep
voltage = ep.phasor(67, 120)
#print(voltage)

# Code which causes failure
voltage = ep.phasor(67, 120)
```

**Expected behavior**
Printing the following:
(-33.499999999999986+58.02370205355739j)

![image](https://github.com/engineerjoe440/ElectricPy/assets/94602350/bcf68914-0e2e-4a4a-b4bb-f8705d0f101f)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04.2 LTS and Windows 10]
 - Python Version [Python 3.10.6]
 - Version [0.2.2]

**Additional context**
If I import it as follows it works and prints the complex representation of voltage value correctly:
```python
import electricpy as ep
voltage = ep.phasor.phasor(67, 120)
print(voltage)
```
![image](https://github.com/engineerjoe440/ElectricPy/assets/94602350/289c9602-5031-4a26-a79f-4155a3201e32)

I've installed electricpy using pip, and I did use pip install --upgrade electricpy to make sure I have the updated version

**Comment by Mogit21** [comment]
At this point, I'm not sure whether I'm using an old version of electricpy, or if there is a typo in the documentation.
In case of a typo in the documentation's example, please let me know, I will be glad to create my first pull request in this project.

**Comment by engineerjoe440** [comment]
Hmm.... It looks like this is a valid bug! Drat! :frowning_face: 

But... I think I can get something put together as a fix!

**Comment by engineerjoe440** [comment]
Ah, yes... this does look like an issue in the documentation. But it raises a good point that none of the examples are being tested. For some strange reason, I thought this was already happening... :laughing: 

Oh well! I'm getting a bit of work done to get that resolved and tidy this up. :wink:

**Comment by engineerjoe440** [comment]
I've been holding off on a release for FAR too long. I'm going to slot this in, along with some other tidying up and general improvements, and get that released!
