### ISSUE TITLE
Sample images are `not` rendered on README.md

### ISSUE THREAD

**Issue by Lakshmikanth2001** [engineerjoe440/ElectricPy#114]
**Describe the bug**

Sample images are `not` rendered on README.md <html>
<body>

Phasor Plot | Power Triangle | Induction Motor Circle
-- | -- | --

</body>
</html>

https://electricpy.readthedocs.io/en/latest/_static/ is giving a 404 response

**Screenshots**
![image](https://github.com/engineerjoe440/ElectricPy/assets/52835045/60f13ddc-da59-4d61-980e-18904f9d2b9d)

**Additional context**

in `gh-pages` branch i am able to see generated images but they are not rendered on REAME.md

**Comment by engineerjoe440** [comment]
Drat! I'm sorry about my delay in response.

Yeah, that is definitely a problem, it seems like there's some configuration issues, here? Not sure. I'm gonna poke around and see what I can come up with.

**Comment by engineerjoe440** [comment]
Sweet! I think we're back up-and-running, now! :)

![image](https://github.com/engineerjoe440/ElectricPy/assets/33275230/196a0efb-494b-4109-8204-91d0cb64cc17)
