### ISSUE TITLE
Parameter Description is cluttered in some function

### ISSUE THREAD

**Issue by Lakshmikanth2001** [engineerjoe440/ElectricPy#17]
### Expected
![electricPy_doc_expected](https://user-images.githubusercontent.com/52835045/131676639-47c1cdc4-7baa-4083-ae34-27c2936fd27e.png)

### For some functions
![electricPy_doc_issue](https://user-images.githubusercontent.com/52835045/131676670-3bd4fac3-ce81-4278-9e6a-35fd120a25b0.png)

**Comment by Lakshmikanth2001** [comment]
We need to add an empty line after every parameter

**Comment by engineerjoe440** [comment]
Hmm... The hanging indent and tight formatting is actually part of the style guide of NumpyDoc: https://numpydoc.readthedocs.io/en/latest/format.html#parameters

I do notice that in my VSCode view, I don't see the same issue that you do. Thus, I wonder if this is, perhaps, more an issue of the editor and extension than it is an issue with the code.
![image](https://user-images.githubusercontent.com/33275230/131772570-5c6cf5ea-d8cb-4baf-bb4a-5c8f40d2a99d.png)

Let me know if you have additional thoughts or questions!
