### ISSUE TITLE
Adding Induction Motor Module in ElectricPy home page

### ISSUE THREAD

**Issue by Lakshmikanth2001** [engineerjoe440/ElectricPy#20]
![image](https://user-images.githubusercontent.com/52835045/135449814-15da2ef8-00b8-41d4-8da9-c8077f750db5.png)

<h1>Please try to add Induction Motor Module on the front page of the ElectricPy documentation</h1>

**Comment by engineerjoe440** [comment]
This is a really good point. I've been trying to think of a better way to integrate the module, I think I've settled on making a "visu" module to help with visualization tools. I'll eventually move other functions to the module, but for now I think this should be a reasonable approach.

**Comment by engineerjoe440** [comment]
Ok! I've touched up a bit of the docs, but getting the sphinx documentation is giving me a bit of a run for my money. I'm gonna call it for now, but this would be worth some more investigation down the road.
