### ISSUE TITLE
Updating GitHub workflow .yaml files 

### ISSUE THREAD

**Issue by Lakshmikanth2001** [engineerjoe440/ElectricPy#24]
![image](https://user-images.githubusercontent.com/52835045/136781422-7905283c-54f8-44cb-aff7-6addf0e3ac6a.png)

after #23  I guess we don't need a separate step to install dependencies `if [ -f requirements.txt ]; then pip install -r 

requirements.txt;`  we can omit that

**Comment by Lakshmikanth2001** [comment]
I have done this in my latest pull request #26

**Comment by engineerjoe440** [comment]
Thank you again for your continued contributions!!! This has been wonderful!
