### ISSUE TITLE
Adding My university 

### ISSUE THREAD

**Issue by Lakshmikanth2001** [engineerjoe440/ElectricPy#27]
![image](https://user-images.githubusercontent.com/52835045/141260205-adb325ef-40e7-413f-9f3a-9f77675d513c.png)

<h3>Can you Please add my university name NIT Warangal (National Institute of Technology Warangal)</h3>

**Comment by engineerjoe440** [comment]
That would be great! I'd be happy to do so!

**Comment by engineerjoe440** [comment]
Done!
