### ISSUE TITLE
Updating engineerjoe440.github.io website

### ISSUE THREAD

**Issue by Lakshmikanth2001** [engineerjoe440/ElectricPy#29]
![image](https://user-images.githubusercontent.com/52835045/143398484-ba654a8b-f0f0-4a23-b27d-587e88f988a6.png)
 <h1>The todo list is not up to date</h1>

**Comment by engineerjoe440** [comment]
Good Point!!!! I've recently learned about some cool functionality that'll suck in the README.md into the Sphinx documentation. I've added that to this branch: https://github.com/engineerjoe440/ElectricPy/tree/enhance-documentation-add-README-content

I think this further highlights the need for the use of a platform like ReadTheDocs to host the documentation of various branches and versions. I'll start investigating this in the new year, but if you have suggestions or ideas. I'd be very happy to hear them!
