### ISSUE TITLE
Source Code url in documentation

### ISSUE THREAD

**Issue by Lakshmikanth2001** [engineerjoe440/ElectricPy#30]
![image](https://user-images.githubusercontent.com/52835045/143407667-1fff85d6-5e87-46fe-9d8e-17a0b852c4c4.png)

Can we have a similar source pointing anchor tag in our https://engineerjoe440.github.io/ElectricPy/api/ documentation page

I have written a python script to generate URL for each function

    function_url =  dict()
    REMOTE_URL = "https://github.com/engineerjoe440/ElectricPy/blob/master/electricpy/"

    #get only files electricpy directory
    SOURCES = [file for file in os.listdir('./electricpy') if os.path.isfile(file)]

    for source in SOURCES:
        with open(os.path.join(sys.path[0], f"electricpy\{source}"), "r") as code:
            # buid a regular expression for "def ()"
            RE = re.compile('def ()')

            # iterate over the lines in the file
            for line_number, line in enumerate(code):
                # find all the functions
                match = RE.findall(line)
                # if there are any matches
                if match:
                    #get text between def and (
                    
                    function_name = line[line.find("def")+4:line.find("(")]

                    function_url[function_name] = f"{REMOTE_URL}{source}#L{line_number+1}"

            with open("urls.json", 'w') as url_data:
                json.dump(function_url, url_data) 

`urls.json` would look similar to this

     "phasorz": "https://github.com/engineerjoe440/ElectricPy/blob/master/electricpy/__init__.py#L844",

https://github.com/engineerjoe440/ElectricPy/blob/master/electricpy/__init__.py#L844 will directly point to the actual function

Can we include this feature

**Comment by engineerjoe440** [comment]
I'm afraid I don't fully understand what you're proposing. I think I like the idea of anchored links, but I'm not sure I see how your proposed implementation fits in.

Where is the `urls.json` file placed, and what does it provide? What references it?

I'll note, there's a subtle improvement that you could add to the RegEx find in your code to find everything up to the first bracket:

```python
RE = re.compile(r'def (.*)\(') # Find all text (function name) up to the open-parenthesis
```

If you'd like to make the modifications in a fork of the repo and open a PR so I can see the results, I'd be very happy to explore more closely! :)

**Comment by Lakshmikanth2001** [comment]
`urls.json` provide hyperlinks for the source code 
 "phasorz": "https://github.com/engineerjoe440/ElectricPy/blob/master/electricpy/__init__.py#L844",

Phasor function source code can be viewed just by clicking this link

**Comment by Lakshmikanth2001** [comment]
`Additional Information
    <https://electrical-engineering-portal.com/download-center/books-and-guides/power-substations/insulator-pollution>`
    
    
![image](https://user-images.githubusercontent.com/52835045/144004089-de711cb9-f58d-44a0-8bb2-961459f85cb8.png)

In  `suspension insulator` we are having `Additional Information` hyperlink

Similarly, we can add a `source` which redirects to source code in GitHub

**Comment by Lakshmikanth2001** [comment]
Sir any update regarding this ???

**Comment by engineerjoe440** [comment]
Please forgive the delay on this issue, I believe you'll see updated documentation in the web documentation now!
