### ISSUE TITLE
Adding Power Circle To ElectricPy

### ISSUE THREAD

**Issue by Lakshmikanth2001** [engineerjoe440/ElectricPy#35]
![PowerCircle](https://user-images.githubusercontent.com/52835045/146339063-41d103b8-d9a9-46c2-9607-0fa9cd77ea35.png)

Can I Add this function in electricpy.visu file

[https://www.youtube.com/watch?v=kGee2B5Pmeg](url)

**Comment by Lakshmikanth2001** [comment]
Sir Any update !!!!!!!!!!!

**Comment by engineerjoe440** [comment]
Forgive my absence! Too much to do around the holiday season, it seems!

Excellent work, we'll want to touch up a few things, but I LOVE this figure! Marvelous!
