### ISSUE TITLE
Format for test functions

### ISSUE THREAD

**Issue by Lakshmikanth2001** [engineerjoe440/ElectricPy#37]
<h2>Can we organized all our test functions in this format</h2>

```
def test_distance():
    
    def test_0():
        p1 = Point(1, 2)
        p2 = Point(3, 4)
        assert geometry.distance(p1, p2) == 2*(2**0.5)

        p1 = Point(4, -6)
        p2 = Point(-2, -5)
        assert geometry.distance(p2, p1) ==  (37**0.5)

        p1 = Point(1.3, 2.3)
        p2 = Point(1.4, 2.4)

        d_output = geometry.distance(p1, p2)
        d_actual = 0.1*(2**0.5)

        assert_array_almost_equal(d_output, d_actual, decimal=6)

    def test_1():
        p1 = Point(1, 2)
        p2 = Point(1, 3)
        assert geometry.distance(p1, p2) == 1

        p1 = Point(2.0, 1)
        p2 = Point(3.0, 1)
        assert geometry.distance(p1, p2) == 1

    for i in range(2):
        exec("test_{}()".format(i))

```
<h2>Where all test function contain at least two test case with increasing level of complexity</h2>

**Comment by Lakshmikanth2001** [comment]
Sir, can you provide your views about this

**Comment by engineerjoe440** [comment]
Hi @Lakshmikanth2001!

Hmm.... I'm struggling to see the purpose of nesting test functions in this paradigm. Would you be able to educate me on the benefit and additional reasoning? I do think that it's valuable to exercise all "corner-cases" of the functionality of the library, but I don't know that I agree with "ramping up" functional tests. I'd rather test the "happy-path" and the corner cases.

That said, I'm interested to hear what the benefit of this pattern is! Perhaps I'm overlooking something valuable!

**Comment by Lakshmikanth2001** [comment]
The Advantages are people can contribute to test cases. First, they will review `test_0` to `test_{i}`  so the complexity of each test case improves they can properly verify where doest their test case fit, or whether the test is already covered by existing methods

**Comment by Lakshmikanth2001** [comment]
Sir Any update regarding this issue

**Comment by engineerjoe440** [comment]
> The Advantages are people can contribute to test cases. First, they will review `test_0` to `test_{i}` so the complexity of each test case improves they can properly verify where doest their test case fit, or whether the test is already covered by existing methods

While that's true, the "pythonic" way to write tests for `pytest` is to write descriptive names to tell what the purpose of the test is. More test-functions can be used for the same core function, and simply be altered to more accurately describe the purpose of the test.

- `test_my_feature_function`
- `test_my_feature_with_input_zero`
- `test_my_feature_with_some_other_value`

**Comment by Lakshmikanth2001** [comment]
We need to make `TestSuiets` to do that, I have to learn how to implement them
