### ISSUE TITLE
Sphinx Build Warning 

### ISSUE THREAD

**Issue by Lakshmikanth2001** [engineerjoe440/ElectricPy#43]
```
WARNING: autodoc: failed to import function 'step' from module 'electricpy'; the following exception was raised:
Traceback (most recent call last):
  File "D:\ElectricProject\ElectricPy\.venv\lib\site-packages\sphinx\util\inspect.py", line 448, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'electricpy' has no attribute 'step'
```
please check out the output of sphinx-build action

**Comment by Lakshmikanth2001** [comment]
Sir any update

**Comment by Lakshmikanth2001** [comment]
Any update sir

**Comment by engineerjoe440** [comment]
Goodness! I thought I had actually responded to this issue. Must not have actually hit submit.

Yes, this is something that I've been meaning to look at, but I've just been putting off. I finally have some time to investigate it today.

**Comment by engineerjoe440** [comment]
Ok! This should be resolved as of my most recent commit to master. I think I still need to do some work to "clean up" the whole auto-api-doc structure. For the moment, however, it's corrected!
