### ISSUE TITLE
Correct NumPy/SciPy/SymPy Casing in Documentation

### ISSUE THREAD

**Issue by engineerjoe440** [engineerjoe440/ElectricPy#51]
In several places throughout the documentation, "NumPy" is not properly capitalized, the same is true for "SciPy" and "SymPy". All three names should be corrected throughout documentation wherever they appear.

**Comment by SaumyaBhushan** [comment]
Can you please assign this task to me?

**Comment by engineerjoe440** [comment]
Wow! Thank you for your responsiveness! :)

I'm going to run the CI on your PR right now and make sure everything works out, then we'll be able to close this. Thank you!

**Comment by engineerjoe440** [comment]
It looks like @SohamRatnaparkhi has actually already opened a PR to address several of these issues. Would you mind verifying that there are no other references that should be updated? I think that we should be in the clear, but I'd greatly appreciate the extra set of eyes.

**Comment by SaumyaBhushan** [comment]
Sure @engineerjoe440 .
