### ISSUE TITLE
Add Automatic Contributor List to README

### ISSUE THREAD

**Issue by engineerjoe440** [engineerjoe440/ElectricPy#61]
There's GOT to be some way to show contributors automatically in the README. So that Github contributors can automatically be listed without needing to be added manually (would save me some time, and make sure people get some of the credit and thanks that they need).

**Comment by asprazz** [comment]
Hi @engineerjoe440, I happen to came accross one repo I recently contributed to having such dynamic feature of listing the contributors just like you mentioned.

https://contrib.rocks/image?repo=engineerjoe440/ElectricPy

I can make PR for the same if its oke

**Comment by engineerjoe440** [comment]
I think this would be great! If you can add that to the "Special Thanks" section, that would be fantastic! You can probably remove those in the list whose images also appear, but the rest should stick around in the list. Thank you!

PR welcome! :)

**Comment by engineerjoe440** [comment]
Just looked up this tool, looks like this is the markdown we'll probably want to use in the README:

```markdown
<a href="https://github.com/engineerjoe440/electricpy/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=engineerjoe440/electricpy" />
</a>

Made with [contrib.rocks](https://contrib.rocks).
```

**Comment by asprazz** [comment]
Yes and a lot of projects are currently using it as its always nice to appreciate those who are giving back to the community.
