### ISSUE TITLE
Add LM317 Formulas

### ISSUE THREAD

**Issue by engineerjoe440** [engineerjoe440/ElectricPy#71]
Would be helpful to add some of the LM317 formulas that are defined at [BasicTables](https://www.basictables.com/electronics/lm317)

**Comment by khan-asfi-reza** [comment]
In which module/file you want this formula to be in? I would like to work on this

**Comment by engineerjoe440** [comment]
Hmm.... this is a good question.

I think we might someday look at combining some stuff to an "`ic`" module, but naming is... well... we're engineers. Has naming things ever *really* been our strong suit? :stuck_out_tongue: 

For now, let's just stick them in the `__init__.py` file, unless you've got a good idea for the name of a module to place them in? Something that could also contain things like the 555-timer functions, etc.

Thank you! :heart:

**Comment by khan-asfi-reza** [comment]
How about keeping these sorts of formulas in a file called `formula.py`

**Comment by engineerjoe440** [comment]
Hmm... Not quite sure about `formula.py` only because I'm thinking we'd want to group the integrated circuit components together as a single module. So I don't think "formula" helps to make that grouping clear.

**Comment by khan-asfi-reza** [comment]
Okay then keeping it in `__init__.py`
