### ISSUE TITLE
Redundant parentheses and comparison to None should be 'if cond is not None':

### ISSUE THREAD

**Issue by khan-asfi-reza** [engineerjoe440/ElectricPy#75]
According to PEP 8 guidance, there must be no redundant parentheses for example
```python
def foo():
  # return (2) # Bad
  return 2 # Good
```
```python
if (value == 2): # Bad
   pass

if value == 2: # Good
  pass
```

Comparison conditions
According to PEP 8: E711 comparison to None should be `if cond is not None`
```python
  if VLL != None: # Bad
      Vm = _np.sqrt(2 / 3) * VLL
```
```python
  if VLL is not None: # Good
      Vm = _np.sqrt(2 / 3) * VLL
```

**Comment by khan-asfi-reza** [comment]
I am working on this issue

**Comment by engineerjoe440** [comment]
Will there be any concern about Python version support with the change from "!=" to "is not"? So long as there won't be any issues, I think that will be fine! Thank you!

**Comment by khan-asfi-reza** [comment]
It will not affect other versions of python. In fact it is supported in python2
