### ISSUE TITLE
Incorrect formula for resistance/reactance in powerimpedance function in __init__.py .

### ISSUE THREAD

**Issue by MrTuckie** [engineerjoe440/ElectricPy#8]
According to [Wikipedia](https://en.wikipedia.org/wiki/AC_power#Calculations_and_equations), using R = (V ** 2 )/P  is only valid when PF = 1 (purely resistive load). If you call the function powerimpedance(S=1111.11,PF=0.9,V=120), it'll return R=14.4 (120²/1000), instead of 11.66 (aprox).

I am currently learning about Circuits and searching for python libraries that could help me during my tests. I'll be very happy to lend a hend if possible in this project.

Best regards.

**Comment by engineerjoe440** [comment]
Hey @MrTuckie!!!

Ah! I'm sure you're on to something, I'll have to dig in and see about making a fix for that (shouldn't be too much). Right now, I can't remember if I'd intended to make that "assumption" regarding the `PF=1` or if I'd intended to more accurately account for the PF. I'll look at it more this weekend, and should be able to get some more info for you!

I'd love to have your contributions in however you see best fit. If that's contributing new functions, fleshing out (improving) existing documentation, or adding automated `pytest` testing, anything will be greatly appreciated. Feel free to jump in wherever and open a pull request to get things drug back in!

**Comment by engineerjoe440** [comment]
Alright! That was a good catch... I'd made a few too many simplifying assumptions and it bit. Thanks for catching it!

The source has been updated in [this commit](https://github.com/engineerjoe440/ElectricPy/commit/98224a5047226944e3d95b621b381a2565b1900c) take a look and see if the [documentation](https://engineerjoe440.github.io/ElectricPy/api/electricpy.powerimpedance.html#electricpy.powerimpedance) seems more appropriate now, and let me know if you have any other questions!

**Comment by MrTuckie** [comment]
Thanks a lot, @engineerjoe440. It seems to be correct now. I am learning about pytest from zero now and I am willing to run some tests with electricpy.

I am an Electric Engineerring Undergrad and studying about electric machines. The problem is that I have zero motivation to study electric motors, unless I put some Python in it 😆 . I am starting a project that makes my life a little bit easier when calculating the parameters during the exams. I hope I will help this library in a way.

Thanks again for sharing your knowledge.

**Comment by engineerjoe440** [comment]
@MrTuckie that sounds FANTASTIC!!! and I can totally relate with the desire to incorporate Python into the monotony of homework and exams. Please feel free to share your expertise in electric machines. I have a small number of formulas related to induction machines, but they're crude at best. Any contributions would be warmly welcomed!!!! :)
