### ISSUE TITLE
`sim.py` Checking isinstance of function, error checking a function 

### ISSUE THREAD

**Issue by khan-asfi-reza** [engineerjoe440/ElectricPy#80]
In `sim.py` [Line:507](https://github.com/engineerjoe440/ElectricPy/blob/976936810c69635bc222ec1d0b2404f64d7d0555/electricpy/sim.py#L507)
checking if `func` is function, will cause error as there is no valid keyword saved as `function` in python.
A valid solution would be 
```python
if callable(func):
```

**Comment by engineerjoe440** [comment]
This is an excellent example of where this project started from, and how it still has plenty of room to grow!

I agree, this is an item that really should be updated.

Long ago, in a University lab-room far, far away, I wrote this without knowing very much about the functions that Python had to support this sort of operation. In fact, it originally used a test like:

```python
if str(type(func)) == "<type function>":
```

Looking back is "fun" but it also makes me cringe. We should fix this ASAP!
